
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING', '201', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING',  '202 ',  '3');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING', '203', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING', '204', '1');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING', '205', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('EASTWING',  '206', '2');


INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '301', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '302', '3');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '303', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '304', '1');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '305', '2');
INSERT INTO ROOM(ROOM_NAME,ROOM_NUMBER,BED_INFO) VALUES ('WESTWING', '306', '2');